// esm-samples/jsapi-vue/src/App.vue
<template>
  <div class="mapdiv"></div>
</template>

<script>
import WebMap from "@arcgis/core/WebMap";
import MapView from "@arcgis/core/views/MapView";
import Bookmarks from "@arcgis/core/widgets/Bookmarks";
import Expand from "@arcgis/core/widgets/Expand"; 

export default {
  name: 'App',
  async mounted() {
    const webmap = new WebMap({
      portalItem: {
        id: "70b726074af04a7e9839d8a07f64c039",
      },
    });

    const view = new MapView({
      // https://v3.vuejs.org/api/instance-properties.html#el
      container: this.$el,
      map: webmap,
    });

    const bookmarks = new Bookmarks({
      view: view
    });

    const bkExpand = new Expand({
      view: view,
      content: bookmarks,
      expanded: true,
    });

    // Add the widget to the top-right corner of the view
    view.ui.add(bkExpand, "top-right");

    // bonus - how many bookmarks in the webmap?
    view.when(function () {
      if (webmap.bookmarks && webmap.bookmarks.length) {
        console.log("Bookmarks: ", webmap.bookmarks.length);
      } else {
        console.log("No bookmarks in this webmap.");
      }
    });
  }
}
</script>

<style scoped>
  @import './main.css';
</style>

// esm-samples/jsapi-custom-ui/src/App.jsx
import { useRef, useEffect, useState } from "react";
import Bookmarks from '@arcgis/core/widgets/Bookmarks.js';
import Expand from '@arcgis/core/widgets/Expand.js';
import MapView from "@arcgis/core/views/MapView.js";
import WebMap from "@arcgis/core/WebMap.js";
import CenterComponent from "./CenterComponent.jsx";

import "./App.css";

function App() {

  const [viewState, setViewState] = useState(null);
  const centerComponentID = useRef("center-component");
  const mapDiv = useRef(null);

  useEffect(() => {
    if (mapDiv.current) {
      const webmap = new WebMap({
        portalItem: {
          id: "70b726074af04a7e9839d8a07f64c039"
        }
      });

      const view = new MapView({
        container: mapDiv.current,
        map: webmap
      });

      const bookmarks = new Bookmarks({
        view
      });

      const bkExpand = new Expand({
        view,
        content: bookmarks,
        expanded: true
      });

      // Add the Expand and BookMarks widgets to the top-right corner of the view
      view.ui.add(bkExpand, "top-right");
      // Add Center component to the bottom-right corner of the view
      view.ui.add(document.getElementById(centerComponentID.current), "bottom-right");

      view.when(() => {
        setViewState({view});
      });
    }
  }, [mapDiv]);

  return <div className="mapDiv" ref={mapDiv}><CenterComponent id={centerComponentID.current} view={viewState}></CenterComponent></div>;
}

export default App;
